cache:
  mount:
    - bundler
build:
  image: ruby:2.2.3
  cache:
    - bundler
  commands:
    - apt-get update -qq
    - gem install rspec
    - apt-get install -y -qq build-essential &>/dev/null
    - bundle install --jobs $(nproc) --path bundler
    - bundle exec rspec --color spec
